### ISSUE TITLE
[WPS4R] Read scripts from symbolic links

### ISSUE THREAD

**Issue by ridoo** [52North/javaPS#27]
I created this issue at the (orphaned?) WPS repository:

https://github.com/52North/WPS/issues/270

To be honest, I am not 100% sure, if it is better described here ... however, this repository hosts the "new generation WPS", so it my get more attention here :smile:

**Comment by bpross-52n** [comment]
Hi ridoo. It is not described better here, as javaPS doesn't contain WPS4R.
