### ISSUE TITLE
JavaPS eating Errors

### ISSUE THREAD

**Issue by overbound** [52North/javaPS#64]
After deploying JavaPS to Tomcat I noticed that I am missing a lot of stracktrace errors. Specifically when I have custom algorithm and it throws an error, this error is never printed in the javaps.log, catalina.out or any other log file that I can find. To work around this issue I am wrapping my execute methods in try catches so that I am able to catch almost all errors.
```java
catch (Exception e) {
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            e.printStackTrace(pw);
            log.error(sw.toString());
}
```
This code allows me to print errors to the javaps.log file. However it would be much nicer if the stacktrace/errors were not eaten at the JavaPS level. Is there a way the codebase can be improved to not eat algorithm errors?

**Comment by bpross-52n** [comment]
Can you give us some code examples? Logging errors seems to work for me, if using an annotated algorithm.

**Comment by overbound** [comment]
Its more accurate to say it eats the stacktraces. When I throw this error JavaPS's default behavior is to show the error code but the stacktrace is lost.

`@Slf4j
@Algorithm(version = "1.0.0")
public class TestAlgorithm {

    private String input;
    private String output;

    @LiteralInput(
            identifier = "input")
    public void setInput(String param) {
        this.input= param;
    }

    @LiteralOutput(
            identifier = "output")
    public String getOutput() {
        return this.output;
    }

    @Execute
    public void runAlgorithm() throws Exception {
        throw new Exception("This is a test error");
    }
}`

Error in javaps.log:
`2020-06-25 09:27:57,645 ERROR o.n.j.e.i.EngineImpl [javaps-0] JobId{value=ea6044c0-145f-46d6-86ed-a7fc3ed853c7} failed: This is a test error`

Desired stackstrace output in javaps.log:
`Caused by: java.lang.Exception: This is a test error
	at com.apexxs.atlas.analytics.elevation.TestAlgorithm .runAlgorithm(ViewshedAlgorithm.java:54) ~[analytics-elevation-javaps-1.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.n52.javaps.algorithm.annotation.ExecuteBinding.execute(ExecuteBinding.java:59) ~[engine-1.6.0-SNAPSHOT.jar:?]
	... 8 more
09:34:43.110 [javaps-0] INFO  org.n52.javaps.engine.impl.EngineImpl - Job '72e15590-b2f0-4949-821b-52231dc09e10' execution finished. Status: Failed;
09:34:43.114 [http-nio-8081-exec-1] TRACE org.n52.iceland.config.spring.ProviderAwareListableBeanFactory - Returning cached instance of singleton bean 'engineExceptionAdvice'`

**Comment by overbound** [comment]
Additionally logging doesn't seem to work unless an error is thrown from my algorithm.

`private String input;
private String output;

@LiteralInput(
        identifier = "input")
public void setInput(String param) {
    this.input= param;
}

@LiteralOutput(
        identifier = "output")
public String getOutput() {
    return this.output;
}

@Execute
public void runAlgorithm() throws Exception {
    log.error("This does not log.");

**Comment by autermann** [comment]
The default log level for `org.n52` loggers is `trace` and for all others (well, except for Spring) it is `warn`.

Unless you changed the [default logging configuration](https://github.com/52North/javaPS/blob/develop/webapp/src/main/resources/log4j2.xml), or if you're using Docker, which has a slightly different [configuration](https://github.com/52North/javaPS/blob/develop/etc/docker-log4j2.xml), the stack trace of each and every exception [should be logged on `debug`](https://github.com/52North/javaPS/blob/develop/engine/src/main/java/org/n52/javaps/engine/impl/EngineImpl.java#L412).

As the log level for the `org.n52.javaps.engine.impl.EngineImpl` logger is trace, the stack trace should definitely appear in your logfile...


Could you show us the `log4j2.xml` that is used?

**Comment by overbound** [comment]
The original log XML file was still overriding my attempts at configurations. I was able to replace the existing log XML and that fixed what I was seeing and makes good sense. So this is a non-issue and I will close. Thanks!
