### ISSUE TITLE
Concurrency issue with LocalAlgorithmRepository

### ISSUE THREAD

**Issue by bpross-52n** [52North/javaPS#66]
In the LocalAlgorithmRepository, algorithms are instantiated only once at the initialization of the repo. The same instance is used by all executions of the algorithm. This leads to race conditions. 

Proposed solution: Each execution needs its own algorithm instance.

**Comment by autermann** [comment]
Actually the algorithm is only used when it was added to the repository as an `IAlgorithm` instance or as an `Object` annotated with `Algorithm`. When added as a `String` or `Class` it was instantiated on [each call](https://github.com/bpross-52n/javaPS/blob/3c12254c2102daf109e2f049fbc8f0a05d378b8f/engine/src/main/java/org/n52/javaps/algorithm/LocalAlgorithmRepository.java#L114).

What if I _want_ to create a thead-safe process, that handles all executions?


Also, [`instance`](https://github.com/52North/javaPS/blob/develop/engine/src/main/java/org/n52/javaps/algorithm/LocalAlgorithmRepository.java#L185) is currently ignored if the instance is of type `IAlgorithm` and no injection is done...

**Comment by autermann** [comment]
Actually is worse. Before, the Identifier of the process could be anything. Now it is only possible to use class names. The `algorithms` map isn't used at all and the the `addAlgorithm` methods do not have an effect and you can instantiate about any class when calling `getAlgorithm`.
